books/Controllers/cadastrarLivrosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using books.Models;

namespace books.Controllers
{
    public class cadastrarLivrosController : Controller
    {
        private contexto db = new contexto();

        // GET: cadastrarLivros
        public ActionResult Index(string sortOrder, string searchString)
        {
            ViewBag.NomeParam = String.IsNullOrEmpty(sortOrder) ? "Nome_Desc" : "";
            ViewBag.StatusParam = sortOrder == "Status" ? "Status_Desc" : "Status";
            var livros = from s in db.Livros
                         select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                livros = livros.Where(s => s.livroName.ToUpper().Contains(searchString.ToUpper()));
            }

            switch(sortOrder)
            {
                case "Nome_desc":
                    livros = livros.OrderByDescending(s => s.livroName);
                        break;
                case "Status":
                    livros = livros.OrderBy(s => s.livroStatus);
                    break;
                case "Status_Desc":
                    livros = livros.OrderByDescending(s => s.livroStatus);
                        break;
                default:
                    livros = livros.OrderBy(s => s.livroName);
                    break;
            }

            return View(db.Livros.ToList());
        }

        // GET: cadastrarLivros/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cadastrarLivros cadastrarLivros = db.Livros.Find(id);
            if (cadastrarLivros == null)
            {
                return HttpNotFound();
            }
            return View(cadastrarLivros);
        }

        // GET: cadastrarLivros/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: cadastrarLivros/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LivroId,livroName,livroGenero,livroStatus")] cadastrarLivros cadastrarLivros)
        {
            if (ModelState.IsValid)
            {
                db.Livros.Add(cadastrarLivros);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cadastrarLivros);
        }

        // GET: cadastrarLivros/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cadastrarLivros cadastrarLivros = db.Livros.Find(id);
            if (cadastrarLivros == null)
            {
                return HttpNotFound();
            }
            return View(cadastrarLivros);
        }

        // POST: cadastrarLivros/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LivroId,livroName,livroGenero,livroStatus")] cadastrarLivros cadastrarLivros)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cadastrarLivros).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cadastrarLivros);
        }

        // GET: cadastrarLivros/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cadastrarLivros cadastrarLivros = db.Livros.Find(id);
            if (cadastrarLivros == null)
            {
                return HttpNotFound();
            }
            return View(cadastrarLivros);
        }

        // POST: cadastrarLivros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            cadastrarLivros cadastrarLivros = db.Livros.Find(id);
            db.Livros.Remove(cadastrarLivros);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

books/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet">
    <link href="/your-path-to-fontawesome/css/brands.css" rel="stylesheet">
    <link href="/your-path-to-fontawesome/css/solid.css" rel="stylesheet">
    <title>@ViewBag.Title - Meus livros em ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <nav class="nvbar">
        <ul class="nvbar-nav">
            <li class="logo">
                <a href="\cadastrarLivros\Index" class="nv-link">
                    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="angle-double-right" class="svg-inline--fa fa-angle-double-right fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M224.3 273l-136 136c-9.4 9.4-24.6 9.4-33.9 0l-22.6-22.6c-9.4-9.4-9.4-24.6 0-33.9l96.4-96.4-96.4-96.4c-9.4-9.4-9.4-24.6 0-33.9L54.3 103c9.4-9.4 24.6-9.4 33.9 0l136 136c9.5 9.4 9.5 24.6.1 34zm192-34l-136-136c-9.4-9.4-24.6-9.4-33.9 0l-22.6 22.6c-9.4 9.4-9.4 24.6 0 33.9l96.4 96.4-96.4 96.4c-9.4 9.4-9.4 24.6 0 33.9l22.6 22.6c9.4 9.4 24.6 9.4 33.9 0l136-136c9.4-9.2 9.4-24.4 0-33.8z"></path></svg>
                    <span class="link-text">BOOKS ASSIST</span>
                </a>
            </li>
            
            <li class="nv-item">
                <a href="\cadastrarLivros\Create" class="nv-link">
                    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="book" class="svg-inline--fa fa-book fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M448 360V24c0-13.3-10.7-24-24-24H96C43 0 0 43 0 96v320c0 53 43 96 96 96h328c13.3 0 24-10.7 24-24v-16c0-7.5-3.5-14.3-8.9-18.7-4.2-15.4-4.2-59.3 0-74.7 5.4-4.3 8.9-11.1 8.9-18.6zM128 134c0-3.3 2.7-6 6-6h212c3.3 0 6 2.7 6 6v20c0 3.3-2.7 6-6 6H134c-3.3 0-6-2.7-6-6v-20zm0 64c0-3.3 2.7-6 6-6h212c3.3 0 6 2.7 6 6v20c0 3.3-2.7 6-6 6H134c-3.3 0-6-2.7-6-6v-20zm253.4 250H96c-17.7 0-32-14.3-32-32 0-17.6 14.4-32 32-32h285.4c-1.9 17.1-1.9 46.9 0 64z"></path></svg>
                    <span class="link-text">Adicionar</span>
                </a>
            </li>
            <li class="nv-item">
                <a href="#" class="nv-link themefy" onclick="CountFun()">
                    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="moon" class="svg-inline--fa fa-moon fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M283.211 512c78.962 0 151.079-35.925 198.857-94.792 7.068-8.708-.639-21.43-11.562-19.35-124.203 23.654-238.262-71.576-238.262-196.954 0-72.222 38.662-138.635 101.498-174.394 9.686-5.512 7.25-20.197-3.756-22.23A258.156 258.156 0 0 0 283.211 0c-141.309 0-256 114.511-256 256 0 141.309 114.511 256 256 256z"></path></svg>
                    <span class="link-text themefy">Change theme</span>
                </a>
            </li>
        </ul>
        </nav>
        <main>

            <!--<div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        @Html.ActionLink("booksASSISTANT", "Index", "cadastrarLivros", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">


                            <li>@Html.ActionLink("Cadastrar livro", "Create", "cadastrarLivros")</li>

                        </ul>



                    </div>
                </div>
            </div>-->
            <div class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year - Meus livros em ASP.NET</p>
                </footer>
            </div>
            <script type="text/javascript">

                var cnt = 0;
                function CountFun() {
                    cnt = parseInt(cnt) + parseInt(1);
                    localStorage.setItem("theme", cnt);

                    if (localStorage.getItem("theme") % 2 === 0) {
                        document.body.style.backgroundColor = "#fff";
                        document.body.style.color = "black";
                    } else {
                        document.body.style.backgroundColor = "#141418";
                        document.body.style.color = "#fff";
                    }
                };
                
            </script>

            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)

        </main>
    
    
</body>
</html>